<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Mohasabi</AssemblyName>
    <RootNamespace>Mohasabi.Launcher</RootNamespace>
    <ApplicationIcon>..\..\assets\mohasabi.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\assets\mohasabi.ico" Link="mohasabi.ico" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\assets\mohasabi.png" Link="mohasabi.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
